backend:
  name: github
  repo: saleshero-inc/saleshero-website
  branch: master

media_folder: "website/static/images" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow
public_folder: "images"
collections:
  - name: "landingpage"
    label: "LandingPage"
    folder: "website/src/pages/lp"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - name: mainBlock
        label: mainBlock
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: markdown}
          - {name: inputPlaceholder, label: InputPlaceholder, widget: string}
          - {name: buttonText, label: ButtonText, widget: string}
          - name: features
            label: Features
            widget: object
            fields:
              - {name: title, label: Title, widget: string}
              - name: items
                label: Items
                widget: list
                fields:
                  - {name: text, label: Text, widget: string}
                  - {name: icon, label: Icon, widget: string}
                  - {name: color, label: Color, widget: string}
      - name: extraBlock
        label: extraBlock
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: markdown}
          - {name: action, label: Action, widget: string}
