backend:
  name: github
  repo: saleshero-inc/saleshero-website
  branch: master

media_folder: "website/static/images" # Media files will be stored in the repo under images/uploads
publish_mode: editorial_workflow
public_folder: "images"
collections:
  - name: "landingpage"
    label: "Landing Page V0"
    folder: "website/src/pages/lp"
    create: true
    slug: "{{slug}}"
    filter:
      field: landingTemplate
      value: Landing
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {name: path, label: Landing Url, widget: string, default: "/lp/"}
      - {name: description, label: Description Metatag, widget: string}
      - {name: keywords, label: Keywords (with comma), widget: string}
      - {name: landingTemplate, label: Template, default: "Landing", widget: "hidden"}
      - name: mainBlock
        label: mainBlock
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: inputPlaceholder, label: InputPlaceholder, widget: string}
          - {name: buttonText, label: ButtonText, widget: string}
      - name: features
        label: Features
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - name: items
            label: Features List
            widget: list
            fields:
              - {name: text, label: Feature Description, widget: string}
              - {name: icon, label: Icon, widget: string}
              - {name: color, label: Color, widget: string}
      - name: extraBlock
        label: extraBlock
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: markdown}
          - {name: inputPlaceholder, label: InputPlaceholder, widget: string}
          - {name: buttonText, label: ButtonText, widget: string}

  - name: "landingpage_v5"
    label: "LandingPageV5"
    folder: "website/src/pages/lp"
    create: true
    slug: "{{slug}}"
    filter:
      field: landingTemplate
      value: Landing_v5
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {name: path, label: Landing Url, widget: string, default: "/lp/"}
      - {name: description, label: Description Metatag, widget: string}
      - {name: keywords, label: Keywords (with comma), widget: string}
      - {name: landingTemplate, label: Template, default: "Landing_v5", widget: "hidden"}
      - name: mainBlock
        label: Title Block
        widget: object
        fields:
          - {name: title, label: Title, widget: textArea}
          - {name: inputPlaceholder, label: Input Placeholder, widget: string}
          - {name: buttonText, label: Button Text, widget: string}
          # - {name: bgImage, label: Background Image url, default: "backgrounds/sales_rep_couch.jpg", widget: string}
      - name: features
        label: Features
        widget: object
        fields:
          - {name: title, label: Title, widget: textArea}
          - name: items
            label: Features
            widget: list
            fields:
              - {name: description, label: Feature Text, widget: string}
              - {name: icon, label: Icon, widget: string}
              - {name: color, label: Icon Color, widget: colorSelector}

  - name: "skills"
    label: "Skills"
    folder: "website/src/pages"
    create: false
    slug: "{{slug}}"
    filter:
      field: title
      value: Skills
    fields:
      - {label: Title, name: title, widget: string, tagname: h1}
      - {name: description, label: Description Metatag, widget: string}
      - {name: keywords, label: Keywords (with comma), widget: string}
      - name: titleBlock
        label: titleBlock
        widget: object
        fields:
          - {name: title, label: Page Title, widget: string}
          - {name: description, label: Page Description, widget: textArea}
      - name: skillsets
        label: Skillsets
        widget: list
        fields:
          - {name: image, label: Skillset Background Image, widget: string}
          # - {name: isColumn, label: IsColumn, widget: boolean}
          - name: skills
            label: Skills
            widget: list
            fields:
              - {name: title, label: Skill Title, widget: string}
              - {name: description, label: Skill Description, widget: textArea}
              - {name: icon, label: Material UI Icon, widget: string}
              - {name: color, label: Icon Color, widget: colorSelector}
      - name: security
        label: Security Section
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: textArea}
          - {name: text, label: Text, widget: textArea}
      - name: extraBlock
        label: Bottom Section
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: textArea}
          - {name: inputPlaceholder, label: Input Placeholder, widget: string}
          - {name: buttonText, label: Button Text, widget: string}

  - name: "home"
    label: "Home"
    folder: "website/src/pages"
    create: false
    slug: "{{slug}}"
    filter:
      field: title
      value: Home Page
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {name: description, label: Description Metatag, widget: string}
      - {name: keywords, label: Keywords (with comma), widget: string}
      - name: mainBlock
        label: MainBlock
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: markdown}
          - {name: inputPlaceholder, label: InputPlaceholder, widget: string}
          - {name: buttonText, label: buttonText, widget: string}
          - {name: message, label: RobinsMessage, widget: string}
      - name: features
        label: Features
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: bgImage, label: BgImage, widget: string}
          - name: items
            label: Items
            widget: list
            fields:
              - {name: title, label: Title, widget: string}
              - {name: description, label: Text, widget: string}
              - {name: icon, label: Icon, widget: string}
              - {name: color, label: Color, widget: colorSelector}

      - name: extraBlock
        label: extraBlock
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: markdown}
          - {name: inputPlaceholder, label: InputPlaceholder, widget: string}
          - {name: buttonText, label: ButtonText, widget: string}

      - name: steps
        label: Steps
        widget: object
        fields:
          - {name: title, label: Title, widget: string}
          - {name: description, label: Description, widget: markdown}
          - {name: successText, label: SuccessText, widget: string}
          - name: items
            label: Items
            widget: list
            fields:
              - {name: text, label: StepText, widget: string}